JNG-3336_Self_not_allowed_in_lambda
BlackBeltTechnology/judo-meta-jsl pull request #107
Opened 2022-12-28 17:51 UTC by gprivi

JNG-3336_Self_not_allowed_in_lambda

2022-12-28 19:32 UTC, robertcsakany requested changes
Plase add tests for lambda self validation.

2022-12-28 19:32 UTC, robertcsakany commented on model/src/main/java/hu/blackbelt/judo/meta/jsl/scoping/JslDslScopeProvider.xtend
> +//				LambdaVariable: return EcoreUtil2.getAllContainers(context).exists[c | c.isEqual(obj.eContainer)] || context.isEqual(obj.eContainer)
Please remove it

2022-12-28 21:36 UTC, gprivi commented on model/src/main/java/hu/blackbelt/judo/meta/jsl/scoping/JslDslScopeProvider.xtend
> +//				LambdaVariable: return EcoreUtil2.getAllContainers(context).exists[c | c.isEqual(obj.eContainer)] || context.isEqual(obj.eContainer)
Done

2022-12-28 23:36 UTC, gprivi commented
> Plase add tests for lambda self validation.

Done

2022-12-29 09:30 UTC, robertcsakany approved these changes

2022-12-29 09:51 UTC, merged