Feature/jng 4498 Release judo jsl
BlackBeltTechnology/judo-meta-jsl pull request #118
Opened 2023-02-28 11:40 UTC by gaborflorian

2023-02-28 14:51 UTC, noherczeg approved these changes

2023-02-28 21:47 UTC, bencegelei requested changes

2023-02-28 21:47 UTC, bencegelei commented on pom.xml
> +                <version>1.2.11</version>
Is this version downgrade intentional?

2023-03-01 09:36 UTC, gaborflorian commented on pom.xml
> +                <version>1.2.11</version>
Requested by Robert

2023-03-01 10:03 UTC, robertcsakany approved these changes

2023-03-01 10:12 UTC, Madmat8 approved these changes

2023-03-01 11:53 UTC, bencegelei approved these changes

2023-03-09 10:22 UTC, merged