JNG-4600 JSL maps and read validations
BlackBeltTechnology/judo-meta-jsl pull request #125
Opened 2023-03-06 11:27 UTC by gprivi

2023-03-06 11:46 UTC, robertcsakany approved these changes

2023-03-06 12:48 UTC, gaborflorian approved these changes

2023-03-06 13:17 UTC, fmagnucz requested changes

2023-03-06 13:17 UTC, fmagnucz commented on model-test/src/test/java/hu/blackbelt/judo/meta/jsl/runtime/TransferTests.xtend
>  }
I would also like to see some positive tests.

2023-03-06 13:17 UTC, fmagnucz commented on model-test/src/test/java/hu/blackbelt/judo/meta/jsl/runtime/TransferTests.xtend
>  }
What about this model?

model Test;

import judo::types;

entity E {}

transfer T(E e) {
	field Integer i reads E!all()!size();
};

The documentation states it is correct.

2023-03-06 13:31 UTC, bencegelei requested changes

2023-03-06 13:31 UTC, bencegelei commented on model-test/src/test/java/hu/blackbelt/judo/meta/jsl/runtime/TransferTests.xtend
>  }
Adding (more) positive test cases would be beneficial, I agree.

2023-03-07 11:26 UTC, gprivi commented on model-test/src/test/java/hu/blackbelt/judo/meta/jsl/runtime/TransferTests.xtend
>  }
@fmagnucz yes, it correct. What is the question?

2023-03-07 11:48 UTC, gprivi commented on model-test/src/test/java/hu/blackbelt/judo/meta/jsl/runtime/TransferTests.xtend
>  }
There is only one positive test. I cannot see that more positive tests are needed. The positive test can be extended on request.

2023-03-07 11:54 UTC, merged